Refactored build success/failure parts and updated README to match. Added failure example to README

diff --git a/shci b/shci
--- a/shci
+++ b/shci
@@ -8,45 +8,65 @@ IFS=$'\n\t'
 BUILD_DIR=$PWD
 BUILD_FILE='.shci.yml'
 
-while getopts ":d:f:v" o; do
+while getopts ":d:f:" o; do
   case $o in
     d) BUILD_DIR=$OPTARG ;;
     f) BUILD_FILE=$OPTARG ;;
-    v) VERBOSE=true ;;
     :) echo "Option -$OPTARG requires an argument." >&2; exit 1 ;;
     *) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
   esac
 done
 
-success() {
+build_result() {
   type=$1
-  echo "$type $FUNCNAME"
-}
+  status=$2
+  cmd=$3
 
-fail() {
-  type=$1
-  echo "$type $FUNCNAME"
+  case $status in
+    success)
+      declare -a \
+        cmds=$(awk '/^failure:/{p=0};p;/^success:/{p=1}' $BUILD_FILE |\
+                 sed -E 's/ .*- //g')
+      ;;
+    failure)
+      declare -a \
+        cmds=$(awk 'p;/^failure:/{p=1}' $BUILD_FILE |\
+                 sed -E 's/ .*- //g')
+      ;;
+    *) echo "Invalid type: $OPTARG" >&2; exit 1
+      ;;
+  esac
+
+  echo "${FUNCNAME}: $type ${status}: $cmd"
+  for cmd in ${cmds[@]}; do
+    eval $cmd
+    if [[ $? -ne "0" ]]; then
+      build_result $type failure $cmd
+      exit 1
+    fi
+  done
 }
 
 build() {
   type=$1
+  fail=0
 
   if [[ -f $BUILD_FILE ]] ; then
     # This is ugly. Should have just used json and jq
     case $type in
       pre)
         declare -a \
-          build_cmds=$(awk '/^build:/{p=0};p;/^pre-build:/{p=1}' $BUILD_FILE |\
+          cmds=$(awk '/^build:/{p=0};p;/^pre-build:/{p=1}' $BUILD_FILE |\
                          sed -E 's/ .*- //g')
         ;;
       build)
         declare -a \
-          build_cmds=$(awk '/^post-build:/{p=0};p;/^build:/{p=1}' $BUILD_FILE |\
+          cmds=$(awk '/^post-build:/{p=0};p;/^build:/{p=1}' $BUILD_FILE |\
                          sed -E 's/ .*- //g')
         ;;
       post)
         declare -a \
-          build_cmds=$(awk 'p;/^post-build:/{p=1}' $BUILD_FILE |\
+          cmds=$(awk '/^success:/{p=0};p;/^post-build:/{p=1}' $BUILD_FILE |\
                          sed -E 's/ .*- //g')
         ;;
       *) echo "Invalid type: $OPTARG" >&2; exit 1 ;;
@@ -57,9 +77,14 @@ build() {
   fi
 
   echo "Performing $type"
-  for cmd in ${build_cmds[@]}; do
+  for cmd in ${cmds[@]}; do
     eval $cmd
+    if [[ $? -ne "0" ]]; then
+      build_result $type failure $cmd
+      exit 1
+    fi
   done
+
 }
 
 main() {
@@ -71,22 +96,13 @@ main() {
   fi
   export BUILD_DIR
 
-  if [[ $VERBOSE ]]; then
-    echo "BUILD_DIR: $BUILD_DIR"
-    echo "GIT_COMMIT: $GIT_COMMIT"
-    echo "GIT_BRANCH: $GIT_BRANCH"
-  fi
-
   declare -a phases=(pre build post)
   for phase in ${phases[@]}; do
     build $phase
-    if [ $? -ne "0" ]; then
-      fail $phase
-      exit 1
-    fi
-    success $phase
     echo
   done
+
+  build_result $type success
 }
 
 main
